#!/usr/bin/env bash

# (c) 2014 by Paul C. Buetow

set -u

declare -r ARG="${1}" ; shift
declare -r QUEUE="${HOME}/.maildelayed"
declare -r NOW=$(date +%s)

usage () {
  cat - <<USAGE >&2
  Usage: $0 mutt|cron
USAGE
}

# Run by a periodic cron job
cron () {
  echo Not yet implemented
  exit 3
}

# Run from mutt
mutt () {
  echo Not yet implemented
  exit 3
}

[ ! -d "${QUEUE}" ] && mkdir "${QUEUE}" && chmod 0700 "${QUEUE}"

case "${ARG}" in
  cron) cron;;
  mutt) mutt;;
  *)    usage;;
esac

exit 0

# vim: filetype=sh
