#!/usr/bin/env bash

# 2015 (c) Paul Buetow

declare -r ARG=$1 ; shift
declare -r DISABLED_FILE=/var/run/autoshutdown.disable

function check {
  if [ -f $DISABLED_FILE ]; then
    echo Autoshutdown is disabled
  else
    echo Autoshutdown is enabled
  fi
}

function disable {
  if [ ! -f $DISABLED_FILE ]; then
    echo Disabling autoshutdown
    sudo touch $DISABLED_FILE
  else
    check
  fi
}

function enable {
  if [ -f $DISABLED_FILE ]; then
    echo Enabling autoshutdown
    sudo rm $DISABLED_FILE
  else
    check
  fi
}

case $ARG in
  enable)
    enable
    ;;
  on)
    enable
    ;;
  disable)
    disable
    ;;
  off)
    disable
    ;;
  *)
    check
    ;;
esac

